name: hommie
version: 1.0.0+1
publish_to: none
description: real estate social platform.
environment: 
  sdk: '>=2.7.0 <3.0.0'
dependencies: 
  cupertino_icons: ^1.0.2
  flutter_svg: ^0.21.0-nullsafety.0

  flutter: 
    sdk: flutter
dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter: 
  assets: 
    - assets/images/
  uses-material-design: true
